  // String firstname = "Mohammed";
  // print(firstname);
  // int age = 16;
  // print(age);
  // print("My first name is $firstname and my age is $age");
  // print(firstname + lastname);
  // bool z = (firstname == lastname);
  // print(z);
  // String name = "Mohammed Elbardan";
  // String phone = "01000000000";
  // String address = "Damnhour";
  // int age = 16;
  // print("My name is $name, my age is $age,\nMy address is $address\nMy phone number is $phone");
  // String accountNumber = "0012478";
  // double money = 1550.5;
  // bool isActive = true;
  // String id = '20305012016070';
  // double increasingPercent = .05;
  // String productName1 = 'The product1';
  // String productName2 = 'The product2';
  // double productPrice1 = 30;
  // double productPrice2 = 20;
  // int productQuantity1 = 2;
  // int productQuantity2 = 3;
  // bool z = (productPrice1 * productQuantity1 == productPrice2 * productQuantity2);
  // print(z);
  // String name = 'Ahmed';
  // name = 'Mohammed';
  // print(name);
  // bool x = name == 'Ahmed';
  // print(x);
  // List names = ['mohammed','khaled','ali'];
  // print(names);
  // names.add('hassan');
  // print(names.length);
  // print(names[3]);
  // names.removeLast();
  // names[2] = 'mahmoud';
  // print(names);
  // List oddNumbers = [[1,3],[5,7],11];
  // print(oddNumbers[1][1]);
  // print(oddNumbers[2]);
  // oddNumbers[0][0] = 13;
  // oddNumbers[1].insert(1, 11);
  // print(oddNumbers);
  // Map data = {"name":"Mohammed","age":16, "adreess":'Damanhour',"job":"Student"};
  // print(data);
  // data["phone"] = '00000000000';
  // data.remove('job');
  // print(data);
  //  Map grades = {"Ali":75,"Mohammed":100,"Retail":100,"Mena":90};
  //  print(grades);
  //  bool x = grades["Ali"] > 75;
  //  print(x);
  //  grades["Rana"] = 50;
  //  print(grades);
  // List y = [grades["Rana"], grades["Mena"]];
  // print(y);
  // y.addAll([[70,60,80],100]);
  // print(y);
  // y[2].insert(1,65);
  // print(y);
  // y.insert(3,90);
  // print(y);
  // y[0] = 95;
  //   print(y);
  // y[2].remove(70);
  // print(y);
  // Map fruits = {"bannana":10,"apple":15,"orange":20};
  // print(fruits);
  // fruits["straberry"] = 25;
  // print(fruits);
  // fruits["apple"] =  30;
  //   print(fruits);
  // List names = ['mohammed','khaled','mahmoud','ali','sami'];
  // print(names.length);
  // print(names[1]);
  // Map user = {'name':names[1],'job':'student','age':16};
  // print(user['age']);
  // int one = 20;
  // int two = 45;
  // int addtion = one + two;
  // int multiple = one * two;
  // int modoul = two % one;
  // int substracting = two - one;
  // double divide = two / one;
  // int roundDivide = two ~/ one;
  // print('The addtion of two number is $addtion');
  // print('The multipling of two number is $multiple');
  // print('The reminder of two number is $modoul');
  // print('The substracting of two number is $substracting');
  // print('The divide of two number is $divide');
  // print('The rounded divide of two number is $roundDivide');
  // print(multiple > addtion);
  // int one = 50;
  // int two = 25;
  // int three = 15;
  // print(one > 100 && one == two && two > one);
  // print(!(one > 100 || one == two || two > one));
//   int long = 15;
//   int width = 30;
//   int result = long * width;
//   print(result);
//   int age = 16;
//  bool hascard = true;
//  bool iscardactive = true;
//  print(age > 18 && hascard && iscardactive);
  // int x = 2;
  // bool result = x % 2 == 0;
  // print(result == 1);
void main(){
  int b = 50;
  int a = b;
  a += b;
  print(a);
  a *= b;
  print(a);
  a ~/= b;
  print(a);
  a %= b;
  print(a);
  a -= b;
  print(a);
  print(a == b);
}